// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biblio.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_biblio_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_biblio_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_biblio_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_biblio_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_biblio_2eproto;
namespace biblio {
class ConsultaResponse;
class ConsultaResponseDefaultTypeInternal;
extern ConsultaResponseDefaultTypeInternal _ConsultaResponse_default_instance_;
class DevolucionResponse;
class DevolucionResponseDefaultTypeInternal;
extern DevolucionResponseDefaultTypeInternal _DevolucionResponse_default_instance_;
class IsbnRequest;
class IsbnRequestDefaultTypeInternal;
extern IsbnRequestDefaultTypeInternal _IsbnRequest_default_instance_;
class PrestamoResponse;
class PrestamoResponseDefaultTypeInternal;
extern PrestamoResponseDefaultTypeInternal _PrestamoResponse_default_instance_;
class TituloRequest;
class TituloRequestDefaultTypeInternal;
extern TituloRequestDefaultTypeInternal _TituloRequest_default_instance_;
}  // namespace biblio
PROTOBUF_NAMESPACE_OPEN
template<> ::biblio::ConsultaResponse* Arena::CreateMaybeMessage<::biblio::ConsultaResponse>(Arena*);
template<> ::biblio::DevolucionResponse* Arena::CreateMaybeMessage<::biblio::DevolucionResponse>(Arena*);
template<> ::biblio::IsbnRequest* Arena::CreateMaybeMessage<::biblio::IsbnRequest>(Arena*);
template<> ::biblio::PrestamoResponse* Arena::CreateMaybeMessage<::biblio::PrestamoResponse>(Arena*);
template<> ::biblio::TituloRequest* Arena::CreateMaybeMessage<::biblio::TituloRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace biblio {

// ===================================================================

class IsbnRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biblio.IsbnRequest) */ {
 public:
  inline IsbnRequest() : IsbnRequest(nullptr) {};
  virtual ~IsbnRequest();

  IsbnRequest(const IsbnRequest& from);
  IsbnRequest(IsbnRequest&& from) noexcept
    : IsbnRequest() {
    *this = ::std::move(from);
  }

  inline IsbnRequest& operator=(const IsbnRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IsbnRequest& operator=(IsbnRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IsbnRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IsbnRequest* internal_default_instance() {
    return reinterpret_cast<const IsbnRequest*>(
               &_IsbnRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IsbnRequest& a, IsbnRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(IsbnRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IsbnRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IsbnRequest* New() const final {
    return CreateMaybeMessage<IsbnRequest>(nullptr);
  }

  IsbnRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IsbnRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IsbnRequest& from);
  void MergeFrom(const IsbnRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IsbnRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biblio.IsbnRequest";
  }
  protected:
  explicit IsbnRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_biblio_2eproto);
    return ::descriptor_table_biblio_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kISBNFieldNumber = 1,
  };
  // int32 ISBN = 1;
  void clear_isbn();
  ::PROTOBUF_NAMESPACE_ID::int32 isbn() const;
  void set_isbn(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_isbn() const;
  void _internal_set_isbn(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:biblio.IsbnRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 isbn_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_biblio_2eproto;
};
// -------------------------------------------------------------------

class TituloRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biblio.TituloRequest) */ {
 public:
  inline TituloRequest() : TituloRequest(nullptr) {};
  virtual ~TituloRequest();

  TituloRequest(const TituloRequest& from);
  TituloRequest(TituloRequest&& from) noexcept
    : TituloRequest() {
    *this = ::std::move(from);
  }

  inline TituloRequest& operator=(const TituloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TituloRequest& operator=(TituloRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TituloRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TituloRequest* internal_default_instance() {
    return reinterpret_cast<const TituloRequest*>(
               &_TituloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TituloRequest& a, TituloRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TituloRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TituloRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TituloRequest* New() const final {
    return CreateMaybeMessage<TituloRequest>(nullptr);
  }

  TituloRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TituloRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TituloRequest& from);
  void MergeFrom(const TituloRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TituloRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biblio.TituloRequest";
  }
  protected:
  explicit TituloRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_biblio_2eproto);
    return ::descriptor_table_biblio_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTituloFieldNumber = 1,
  };
  // string titulo = 1;
  void clear_titulo();
  const std::string& titulo() const;
  void set_titulo(const std::string& value);
  void set_titulo(std::string&& value);
  void set_titulo(const char* value);
  void set_titulo(const char* value, size_t size);
  std::string* mutable_titulo();
  std::string* release_titulo();
  void set_allocated_titulo(std::string* titulo);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_titulo();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_titulo(
      std::string* titulo);
  private:
  const std::string& _internal_titulo() const;
  void _internal_set_titulo(const std::string& value);
  std::string* _internal_mutable_titulo();
  public:

  // @@protoc_insertion_point(class_scope:biblio.TituloRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr titulo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_biblio_2eproto;
};
// -------------------------------------------------------------------

class PrestamoResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biblio.PrestamoResponse) */ {
 public:
  inline PrestamoResponse() : PrestamoResponse(nullptr) {};
  virtual ~PrestamoResponse();

  PrestamoResponse(const PrestamoResponse& from);
  PrestamoResponse(PrestamoResponse&& from) noexcept
    : PrestamoResponse() {
    *this = ::std::move(from);
  }

  inline PrestamoResponse& operator=(const PrestamoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrestamoResponse& operator=(PrestamoResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrestamoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrestamoResponse* internal_default_instance() {
    return reinterpret_cast<const PrestamoResponse*>(
               &_PrestamoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PrestamoResponse& a, PrestamoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PrestamoResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrestamoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrestamoResponse* New() const final {
    return CreateMaybeMessage<PrestamoResponse>(nullptr);
  }

  PrestamoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrestamoResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrestamoResponse& from);
  void MergeFrom(const PrestamoResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrestamoResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biblio.PrestamoResponse";
  }
  protected:
  explicit PrestamoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_biblio_2eproto);
    return ::descriptor_table_biblio_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFechaFieldNumber = 2,
    kEstadoFieldNumber = 1,
  };
  // string fecha = 2;
  void clear_fecha();
  const std::string& fecha() const;
  void set_fecha(const std::string& value);
  void set_fecha(std::string&& value);
  void set_fecha(const char* value);
  void set_fecha(const char* value, size_t size);
  std::string* mutable_fecha();
  std::string* release_fecha();
  void set_allocated_fecha(std::string* fecha);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fecha();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fecha(
      std::string* fecha);
  private:
  const std::string& _internal_fecha() const;
  void _internal_set_fecha(const std::string& value);
  std::string* _internal_mutable_fecha();
  public:

  // bool estado = 1;
  void clear_estado();
  bool estado() const;
  void set_estado(bool value);
  private:
  bool _internal_estado() const;
  void _internal_set_estado(bool value);
  public:

  // @@protoc_insertion_point(class_scope:biblio.PrestamoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fecha_;
  bool estado_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_biblio_2eproto;
};
// -------------------------------------------------------------------

class ConsultaResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biblio.ConsultaResponse) */ {
 public:
  inline ConsultaResponse() : ConsultaResponse(nullptr) {};
  virtual ~ConsultaResponse();

  ConsultaResponse(const ConsultaResponse& from);
  ConsultaResponse(ConsultaResponse&& from) noexcept
    : ConsultaResponse() {
    *this = ::std::move(from);
  }

  inline ConsultaResponse& operator=(const ConsultaResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConsultaResponse& operator=(ConsultaResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConsultaResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConsultaResponse* internal_default_instance() {
    return reinterpret_cast<const ConsultaResponse*>(
               &_ConsultaResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ConsultaResponse& a, ConsultaResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ConsultaResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConsultaResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConsultaResponse* New() const final {
    return CreateMaybeMessage<ConsultaResponse>(nullptr);
  }

  ConsultaResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConsultaResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConsultaResponse& from);
  void MergeFrom(const ConsultaResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConsultaResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biblio.ConsultaResponse";
  }
  protected:
  explicit ConsultaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_biblio_2eproto);
    return ::descriptor_table_biblio_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEstadoFieldNumber = 1,
    kDisponiblesFieldNumber = 2,
  };
  // bool estado = 1;
  void clear_estado();
  bool estado() const;
  void set_estado(bool value);
  private:
  bool _internal_estado() const;
  void _internal_set_estado(bool value);
  public:

  // int32 disponibles = 2;
  void clear_disponibles();
  ::PROTOBUF_NAMESPACE_ID::int32 disponibles() const;
  void set_disponibles(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_disponibles() const;
  void _internal_set_disponibles(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:biblio.ConsultaResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool estado_;
  ::PROTOBUF_NAMESPACE_ID::int32 disponibles_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_biblio_2eproto;
};
// -------------------------------------------------------------------

class DevolucionResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:biblio.DevolucionResponse) */ {
 public:
  inline DevolucionResponse() : DevolucionResponse(nullptr) {};
  virtual ~DevolucionResponse();

  DevolucionResponse(const DevolucionResponse& from);
  DevolucionResponse(DevolucionResponse&& from) noexcept
    : DevolucionResponse() {
    *this = ::std::move(from);
  }

  inline DevolucionResponse& operator=(const DevolucionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DevolucionResponse& operator=(DevolucionResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DevolucionResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DevolucionResponse* internal_default_instance() {
    return reinterpret_cast<const DevolucionResponse*>(
               &_DevolucionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(DevolucionResponse& a, DevolucionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DevolucionResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DevolucionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DevolucionResponse* New() const final {
    return CreateMaybeMessage<DevolucionResponse>(nullptr);
  }

  DevolucionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DevolucionResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DevolucionResponse& from);
  void MergeFrom(const DevolucionResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DevolucionResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "biblio.DevolucionResponse";
  }
  protected:
  explicit DevolucionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_biblio_2eproto);
    return ::descriptor_table_biblio_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEstadoFieldNumber = 1,
  };
  // bool estado = 1;
  void clear_estado();
  bool estado() const;
  void set_estado(bool value);
  private:
  bool _internal_estado() const;
  void _internal_set_estado(bool value);
  public:

  // @@protoc_insertion_point(class_scope:biblio.DevolucionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool estado_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_biblio_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IsbnRequest

// int32 ISBN = 1;
inline void IsbnRequest::clear_isbn() {
  isbn_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IsbnRequest::_internal_isbn() const {
  return isbn_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IsbnRequest::isbn() const {
  // @@protoc_insertion_point(field_get:biblio.IsbnRequest.ISBN)
  return _internal_isbn();
}
inline void IsbnRequest::_internal_set_isbn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  isbn_ = value;
}
inline void IsbnRequest::set_isbn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_isbn(value);
  // @@protoc_insertion_point(field_set:biblio.IsbnRequest.ISBN)
}

// -------------------------------------------------------------------

// TituloRequest

// string titulo = 1;
inline void TituloRequest::clear_titulo() {
  titulo_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TituloRequest::titulo() const {
  // @@protoc_insertion_point(field_get:biblio.TituloRequest.titulo)
  return _internal_titulo();
}
inline void TituloRequest::set_titulo(const std::string& value) {
  _internal_set_titulo(value);
  // @@protoc_insertion_point(field_set:biblio.TituloRequest.titulo)
}
inline std::string* TituloRequest::mutable_titulo() {
  // @@protoc_insertion_point(field_mutable:biblio.TituloRequest.titulo)
  return _internal_mutable_titulo();
}
inline const std::string& TituloRequest::_internal_titulo() const {
  return titulo_.Get();
}
inline void TituloRequest::_internal_set_titulo(const std::string& value) {
  
  titulo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TituloRequest::set_titulo(std::string&& value) {
  
  titulo_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:biblio.TituloRequest.titulo)
}
inline void TituloRequest::set_titulo(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  titulo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:biblio.TituloRequest.titulo)
}
inline void TituloRequest::set_titulo(const char* value,
    size_t size) {
  
  titulo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:biblio.TituloRequest.titulo)
}
inline std::string* TituloRequest::_internal_mutable_titulo() {
  
  return titulo_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TituloRequest::release_titulo() {
  // @@protoc_insertion_point(field_release:biblio.TituloRequest.titulo)
  return titulo_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TituloRequest::set_allocated_titulo(std::string* titulo) {
  if (titulo != nullptr) {
    
  } else {
    
  }
  titulo_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), titulo,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:biblio.TituloRequest.titulo)
}
inline std::string* TituloRequest::unsafe_arena_release_titulo() {
  // @@protoc_insertion_point(field_unsafe_arena_release:biblio.TituloRequest.titulo)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return titulo_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TituloRequest::unsafe_arena_set_allocated_titulo(
    std::string* titulo) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (titulo != nullptr) {
    
  } else {
    
  }
  titulo_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      titulo, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biblio.TituloRequest.titulo)
}

// -------------------------------------------------------------------

// PrestamoResponse

// bool estado = 1;
inline void PrestamoResponse::clear_estado() {
  estado_ = false;
}
inline bool PrestamoResponse::_internal_estado() const {
  return estado_;
}
inline bool PrestamoResponse::estado() const {
  // @@protoc_insertion_point(field_get:biblio.PrestamoResponse.estado)
  return _internal_estado();
}
inline void PrestamoResponse::_internal_set_estado(bool value) {
  
  estado_ = value;
}
inline void PrestamoResponse::set_estado(bool value) {
  _internal_set_estado(value);
  // @@protoc_insertion_point(field_set:biblio.PrestamoResponse.estado)
}

// string fecha = 2;
inline void PrestamoResponse::clear_fecha() {
  fecha_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PrestamoResponse::fecha() const {
  // @@protoc_insertion_point(field_get:biblio.PrestamoResponse.fecha)
  return _internal_fecha();
}
inline void PrestamoResponse::set_fecha(const std::string& value) {
  _internal_set_fecha(value);
  // @@protoc_insertion_point(field_set:biblio.PrestamoResponse.fecha)
}
inline std::string* PrestamoResponse::mutable_fecha() {
  // @@protoc_insertion_point(field_mutable:biblio.PrestamoResponse.fecha)
  return _internal_mutable_fecha();
}
inline const std::string& PrestamoResponse::_internal_fecha() const {
  return fecha_.Get();
}
inline void PrestamoResponse::_internal_set_fecha(const std::string& value) {
  
  fecha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PrestamoResponse::set_fecha(std::string&& value) {
  
  fecha_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:biblio.PrestamoResponse.fecha)
}
inline void PrestamoResponse::set_fecha(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fecha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:biblio.PrestamoResponse.fecha)
}
inline void PrestamoResponse::set_fecha(const char* value,
    size_t size) {
  
  fecha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:biblio.PrestamoResponse.fecha)
}
inline std::string* PrestamoResponse::_internal_mutable_fecha() {
  
  return fecha_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PrestamoResponse::release_fecha() {
  // @@protoc_insertion_point(field_release:biblio.PrestamoResponse.fecha)
  return fecha_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrestamoResponse::set_allocated_fecha(std::string* fecha) {
  if (fecha != nullptr) {
    
  } else {
    
  }
  fecha_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fecha,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:biblio.PrestamoResponse.fecha)
}
inline std::string* PrestamoResponse::unsafe_arena_release_fecha() {
  // @@protoc_insertion_point(field_unsafe_arena_release:biblio.PrestamoResponse.fecha)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return fecha_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PrestamoResponse::unsafe_arena_set_allocated_fecha(
    std::string* fecha) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fecha != nullptr) {
    
  } else {
    
  }
  fecha_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fecha, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:biblio.PrestamoResponse.fecha)
}

// -------------------------------------------------------------------

// ConsultaResponse

// bool estado = 1;
inline void ConsultaResponse::clear_estado() {
  estado_ = false;
}
inline bool ConsultaResponse::_internal_estado() const {
  return estado_;
}
inline bool ConsultaResponse::estado() const {
  // @@protoc_insertion_point(field_get:biblio.ConsultaResponse.estado)
  return _internal_estado();
}
inline void ConsultaResponse::_internal_set_estado(bool value) {
  
  estado_ = value;
}
inline void ConsultaResponse::set_estado(bool value) {
  _internal_set_estado(value);
  // @@protoc_insertion_point(field_set:biblio.ConsultaResponse.estado)
}

// int32 disponibles = 2;
inline void ConsultaResponse::clear_disponibles() {
  disponibles_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ConsultaResponse::_internal_disponibles() const {
  return disponibles_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ConsultaResponse::disponibles() const {
  // @@protoc_insertion_point(field_get:biblio.ConsultaResponse.disponibles)
  return _internal_disponibles();
}
inline void ConsultaResponse::_internal_set_disponibles(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  disponibles_ = value;
}
inline void ConsultaResponse::set_disponibles(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_disponibles(value);
  // @@protoc_insertion_point(field_set:biblio.ConsultaResponse.disponibles)
}

// -------------------------------------------------------------------

// DevolucionResponse

// bool estado = 1;
inline void DevolucionResponse::clear_estado() {
  estado_ = false;
}
inline bool DevolucionResponse::_internal_estado() const {
  return estado_;
}
inline bool DevolucionResponse::estado() const {
  // @@protoc_insertion_point(field_get:biblio.DevolucionResponse.estado)
  return _internal_estado();
}
inline void DevolucionResponse::_internal_set_estado(bool value) {
  
  estado_ = value;
}
inline void DevolucionResponse::set_estado(bool value) {
  _internal_set_estado(value);
  // @@protoc_insertion_point(field_set:biblio.DevolucionResponse.estado)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace biblio

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_biblio_2eproto
