// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: biblio.proto

#include "biblio.pb.h"
#include "biblio.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace biblio {

static const char* Biblioteca_method_names[] = {
  "/biblio.Biblioteca/PrestamoISBN",
  "/biblio.Biblioteca/PrestamoTitulo",
  "/biblio.Biblioteca/ConsultaISBN",
  "/biblio.Biblioteca/DevolucionISBN",
};

std::unique_ptr< Biblioteca::Stub> Biblioteca::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Biblioteca::Stub> stub(new Biblioteca::Stub(channel));
  return stub;
}

Biblioteca::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PrestamoISBN_(Biblioteca_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PrestamoTitulo_(Biblioteca_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConsultaISBN_(Biblioteca_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DevolucionISBN_(Biblioteca_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Biblioteca::Stub::PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::PrestamoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PrestamoISBN_, context, request, response);
}

void Biblioteca::Stub::experimental_async::PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoISBN_, context, request, response, reactor);
}

void Biblioteca::Stub::experimental_async::PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoISBN_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* Biblioteca::Stub::AsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::PrestamoResponse>::Create(channel_.get(), cq, rpcmethod_PrestamoISBN_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* Biblioteca::Stub::PrepareAsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::PrestamoResponse>::Create(channel_.get(), cq, rpcmethod_PrestamoISBN_, context, request, false);
}

::grpc::Status Biblioteca::Stub::PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::biblio::PrestamoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PrestamoTitulo_, context, request, response);
}

void Biblioteca::Stub::experimental_async::PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoTitulo_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PrestamoTitulo_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoTitulo_, context, request, response, reactor);
}

void Biblioteca::Stub::experimental_async::PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PrestamoTitulo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* Biblioteca::Stub::AsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::PrestamoResponse>::Create(channel_.get(), cq, rpcmethod_PrestamoTitulo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* Biblioteca::Stub::PrepareAsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::PrestamoResponse>::Create(channel_.get(), cq, rpcmethod_PrestamoTitulo_, context, request, false);
}

::grpc::Status Biblioteca::Stub::ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::ConsultaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ConsultaISBN_, context, request, response);
}

void Biblioteca::Stub::experimental_async::ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ConsultaISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ConsultaISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ConsultaISBN_, context, request, response, reactor);
}

void Biblioteca::Stub::experimental_async::ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ConsultaISBN_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>* Biblioteca::Stub::AsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::ConsultaResponse>::Create(channel_.get(), cq, rpcmethod_ConsultaISBN_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>* Biblioteca::Stub::PrepareAsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::ConsultaResponse>::Create(channel_.get(), cq, rpcmethod_ConsultaISBN_, context, request, false);
}

::grpc::Status Biblioteca::Stub::DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::DevolucionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DevolucionISBN_, context, request, response);
}

void Biblioteca::Stub::experimental_async::DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DevolucionISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DevolucionISBN_, context, request, response, std::move(f));
}

void Biblioteca::Stub::experimental_async::DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DevolucionISBN_, context, request, response, reactor);
}

void Biblioteca::Stub::experimental_async::DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DevolucionISBN_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>* Biblioteca::Stub::AsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::DevolucionResponse>::Create(channel_.get(), cq, rpcmethod_DevolucionISBN_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>* Biblioteca::Stub::PrepareAsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::biblio::DevolucionResponse>::Create(channel_.get(), cq, rpcmethod_DevolucionISBN_, context, request, false);
}

Biblioteca::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Biblioteca_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Biblioteca::Service, ::biblio::IsbnRequest, ::biblio::PrestamoResponse>(
          [](Biblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblio::IsbnRequest* req,
             ::biblio::PrestamoResponse* resp) {
               return service->PrestamoISBN(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Biblioteca_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Biblioteca::Service, ::biblio::TituloRequest, ::biblio::PrestamoResponse>(
          [](Biblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblio::TituloRequest* req,
             ::biblio::PrestamoResponse* resp) {
               return service->PrestamoTitulo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Biblioteca_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Biblioteca::Service, ::biblio::IsbnRequest, ::biblio::ConsultaResponse>(
          [](Biblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblio::IsbnRequest* req,
             ::biblio::ConsultaResponse* resp) {
               return service->ConsultaISBN(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Biblioteca_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Biblioteca::Service, ::biblio::IsbnRequest, ::biblio::DevolucionResponse>(
          [](Biblioteca::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::biblio::IsbnRequest* req,
             ::biblio::DevolucionResponse* resp) {
               return service->DevolucionISBN(ctx, req, resp);
             }, this)));
}

Biblioteca::Service::~Service() {
}

::grpc::Status Biblioteca::Service::PrestamoISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Biblioteca::Service::PrestamoTitulo(::grpc::ServerContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Biblioteca::Service::ConsultaISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Biblioteca::Service::DevolucionISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace biblio

