// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: biblio.proto
#ifndef GRPC_biblio_2eproto__INCLUDED
#define GRPC_biblio_2eproto__INCLUDED

#include "biblio.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace biblio {

class Biblioteca final {
 public:
  static constexpr char const* service_full_name() {
    return "biblio.Biblioteca";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::PrestamoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>> AsyncPrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>>(AsyncPrestamoISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>> PrepareAsyncPrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>>(PrepareAsyncPrestamoISBNRaw(context, request, cq));
    }
    virtual ::grpc::Status PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::biblio::PrestamoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>> AsyncPrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>>(AsyncPrestamoTituloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>> PrepareAsyncPrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>>(PrepareAsyncPrestamoTituloRaw(context, request, cq));
    }
    virtual ::grpc::Status ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::ConsultaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>> AsyncConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>>(AsyncConsultaISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>> PrepareAsyncConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>>(PrepareAsyncConsultaISBNRaw(context, request, cq));
    }
    virtual ::grpc::Status DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::DevolucionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>> AsyncDevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>>(AsyncDevolucionISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>> PrepareAsyncDevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>>(PrepareAsyncDevolucionISBNRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>* AsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>* PrepareAsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>* AsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::PrestamoResponse>* PrepareAsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>* AsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::ConsultaResponse>* PrepareAsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>* AsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::biblio::DevolucionResponse>* PrepareAsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::PrestamoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>> AsyncPrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>>(AsyncPrestamoISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>> PrepareAsyncPrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>>(PrepareAsyncPrestamoISBNRaw(context, request, cq));
    }
    ::grpc::Status PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::biblio::PrestamoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>> AsyncPrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>>(AsyncPrestamoTituloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>> PrepareAsyncPrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>>(PrepareAsyncPrestamoTituloRaw(context, request, cq));
    }
    ::grpc::Status ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::ConsultaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>> AsyncConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>>(AsyncConsultaISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>> PrepareAsyncConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>>(PrepareAsyncConsultaISBNRaw(context, request, cq));
    }
    ::grpc::Status DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::biblio::DevolucionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>> AsyncDevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>>(AsyncDevolucionISBNRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>> PrepareAsyncDevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>>(PrepareAsyncDevolucionISBNRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) override;
      void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) override;
      void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoTitulo(::grpc::ClientContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PrestamoTitulo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::PrestamoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)>) override;
      void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ConsultaISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ConsultaISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::ConsultaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)>) override;
      void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DevolucionISBN(::grpc::ClientContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DevolucionISBN(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::biblio::DevolucionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* AsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* PrepareAsyncPrestamoISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* AsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::PrestamoResponse>* PrepareAsyncPrestamoTituloRaw(::grpc::ClientContext* context, const ::biblio::TituloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>* AsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::ConsultaResponse>* PrepareAsyncConsultaISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>* AsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::biblio::DevolucionResponse>* PrepareAsyncDevolucionISBNRaw(::grpc::ClientContext* context, const ::biblio::IsbnRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PrestamoISBN_;
    const ::grpc::internal::RpcMethod rpcmethod_PrestamoTitulo_;
    const ::grpc::internal::RpcMethod rpcmethod_ConsultaISBN_;
    const ::grpc::internal::RpcMethod rpcmethod_DevolucionISBN_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PrestamoISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response);
    virtual ::grpc::Status PrestamoTitulo(::grpc::ServerContext* context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response);
    virtual ::grpc::Status ConsultaISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response);
    virtual ::grpc::Status DevolucionISBN(::grpc::ServerContext* context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrestamoISBN() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoISBN(::grpc::ServerContext* context, ::biblio::IsbnRequest* request, ::grpc::ServerAsyncResponseWriter< ::biblio::PrestamoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrestamoTitulo() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoTitulo(::grpc::ServerContext* context, ::biblio::TituloRequest* request, ::grpc::ServerAsyncResponseWriter< ::biblio::PrestamoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ConsultaISBN() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsultaISBN(::grpc::ServerContext* context, ::biblio::IsbnRequest* request, ::grpc::ServerAsyncResponseWriter< ::biblio::ConsultaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DevolucionISBN() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDevolucionISBN(::grpc::ServerContext* context, ::biblio::IsbnRequest* request, ::grpc::ServerAsyncResponseWriter< ::biblio::DevolucionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PrestamoISBN<WithAsyncMethod_PrestamoTitulo<WithAsyncMethod_ConsultaISBN<WithAsyncMethod_DevolucionISBN<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PrestamoISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::PrestamoResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblio::IsbnRequest* request, ::biblio::PrestamoResponse* response) { return this->PrestamoISBN(context, request, response); }));}
    void SetMessageAllocatorFor_PrestamoISBN(
        ::grpc::experimental::MessageAllocator< ::biblio::IsbnRequest, ::biblio::PrestamoResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::PrestamoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PrestamoTitulo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblio::TituloRequest, ::biblio::PrestamoResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblio::TituloRequest* request, ::biblio::PrestamoResponse* response) { return this->PrestamoTitulo(context, request, response); }));}
    void SetMessageAllocatorFor_PrestamoTitulo(
        ::grpc::experimental::MessageAllocator< ::biblio::TituloRequest, ::biblio::PrestamoResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblio::TituloRequest, ::biblio::PrestamoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoTitulo(
      ::grpc::CallbackServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoTitulo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ConsultaISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::ConsultaResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblio::IsbnRequest* request, ::biblio::ConsultaResponse* response) { return this->ConsultaISBN(context, request, response); }));}
    void SetMessageAllocatorFor_ConsultaISBN(
        ::grpc::experimental::MessageAllocator< ::biblio::IsbnRequest, ::biblio::ConsultaResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::ConsultaResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ConsultaISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ConsultaISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DevolucionISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::DevolucionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::biblio::IsbnRequest* request, ::biblio::DevolucionResponse* response) { return this->DevolucionISBN(context, request, response); }));}
    void SetMessageAllocatorFor_DevolucionISBN(
        ::grpc::experimental::MessageAllocator< ::biblio::IsbnRequest, ::biblio::DevolucionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::biblio::IsbnRequest, ::biblio::DevolucionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DevolucionISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DevolucionISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_PrestamoISBN<ExperimentalWithCallbackMethod_PrestamoTitulo<ExperimentalWithCallbackMethod_ConsultaISBN<ExperimentalWithCallbackMethod_DevolucionISBN<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_PrestamoISBN<ExperimentalWithCallbackMethod_PrestamoTitulo<ExperimentalWithCallbackMethod_ConsultaISBN<ExperimentalWithCallbackMethod_DevolucionISBN<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrestamoISBN() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrestamoTitulo() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ConsultaISBN() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DevolucionISBN() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrestamoISBN() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoISBN(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrestamoTitulo() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrestamoTitulo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ConsultaISBN() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsultaISBN(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DevolucionISBN() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDevolucionISBN(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PrestamoISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrestamoISBN(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PrestamoTitulo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrestamoTitulo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PrestamoTitulo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PrestamoTitulo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ConsultaISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ConsultaISBN(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ConsultaISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ConsultaISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DevolucionISBN() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DevolucionISBN(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DevolucionISBN(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DevolucionISBN(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrestamoISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrestamoISBN() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblio::IsbnRequest, ::biblio::PrestamoResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblio::IsbnRequest, ::biblio::PrestamoResponse>* streamer) {
                       return this->StreamedPrestamoISBN(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrestamoISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrestamoISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrestamoISBN(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblio::IsbnRequest,::biblio::PrestamoResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrestamoTitulo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrestamoTitulo() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblio::TituloRequest, ::biblio::PrestamoResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblio::TituloRequest, ::biblio::PrestamoResponse>* streamer) {
                       return this->StreamedPrestamoTitulo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrestamoTitulo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrestamoTitulo(::grpc::ServerContext* /*context*/, const ::biblio::TituloRequest* /*request*/, ::biblio::PrestamoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrestamoTitulo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblio::TituloRequest,::biblio::PrestamoResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ConsultaISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ConsultaISBN() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblio::IsbnRequest, ::biblio::ConsultaResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblio::IsbnRequest, ::biblio::ConsultaResponse>* streamer) {
                       return this->StreamedConsultaISBN(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ConsultaISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ConsultaISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::ConsultaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConsultaISBN(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblio::IsbnRequest,::biblio::ConsultaResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DevolucionISBN : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DevolucionISBN() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::biblio::IsbnRequest, ::biblio::DevolucionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::biblio::IsbnRequest, ::biblio::DevolucionResponse>* streamer) {
                       return this->StreamedDevolucionISBN(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DevolucionISBN() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DevolucionISBN(::grpc::ServerContext* /*context*/, const ::biblio::IsbnRequest* /*request*/, ::biblio::DevolucionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDevolucionISBN(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::biblio::IsbnRequest,::biblio::DevolucionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PrestamoISBN<WithStreamedUnaryMethod_PrestamoTitulo<WithStreamedUnaryMethod_ConsultaISBN<WithStreamedUnaryMethod_DevolucionISBN<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PrestamoISBN<WithStreamedUnaryMethod_PrestamoTitulo<WithStreamedUnaryMethod_ConsultaISBN<WithStreamedUnaryMethod_DevolucionISBN<Service > > > > StreamedService;
};

}  // namespace biblio


#endif  // GRPC_biblio_2eproto__INCLUDED
