// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biblio.proto

#include "biblio.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace biblio {
class IsbnRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IsbnRequest> _instance;
} _IsbnRequest_default_instance_;
class TituloRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TituloRequest> _instance;
} _TituloRequest_default_instance_;
class PrestamoResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PrestamoResponse> _instance;
} _PrestamoResponse_default_instance_;
class ConsultaResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConsultaResponse> _instance;
} _ConsultaResponse_default_instance_;
class DevolucionResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DevolucionResponse> _instance;
} _DevolucionResponse_default_instance_;
}  // namespace biblio
static void InitDefaultsscc_info_ConsultaResponse_biblio_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblio::_ConsultaResponse_default_instance_;
    new (ptr) ::biblio::ConsultaResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblio::ConsultaResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConsultaResponse_biblio_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConsultaResponse_biblio_2eproto}, {}};

static void InitDefaultsscc_info_DevolucionResponse_biblio_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblio::_DevolucionResponse_default_instance_;
    new (ptr) ::biblio::DevolucionResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblio::DevolucionResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DevolucionResponse_biblio_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DevolucionResponse_biblio_2eproto}, {}};

static void InitDefaultsscc_info_IsbnRequest_biblio_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblio::_IsbnRequest_default_instance_;
    new (ptr) ::biblio::IsbnRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblio::IsbnRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_IsbnRequest_biblio_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_IsbnRequest_biblio_2eproto}, {}};

static void InitDefaultsscc_info_PrestamoResponse_biblio_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblio::_PrestamoResponse_default_instance_;
    new (ptr) ::biblio::PrestamoResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblio::PrestamoResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PrestamoResponse_biblio_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PrestamoResponse_biblio_2eproto}, {}};

static void InitDefaultsscc_info_TituloRequest_biblio_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biblio::_TituloRequest_default_instance_;
    new (ptr) ::biblio::TituloRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biblio::TituloRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TituloRequest_biblio_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TituloRequest_biblio_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_biblio_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_biblio_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_biblio_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_biblio_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblio::IsbnRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblio::IsbnRequest, isbn_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblio::TituloRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblio::TituloRequest, titulo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblio::PrestamoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblio::PrestamoResponse, estado_),
  PROTOBUF_FIELD_OFFSET(::biblio::PrestamoResponse, fecha_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblio::ConsultaResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblio::ConsultaResponse, estado_),
  PROTOBUF_FIELD_OFFSET(::biblio::ConsultaResponse, disponibles_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::biblio::DevolucionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::biblio::DevolucionResponse, estado_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::biblio::IsbnRequest)},
  { 6, -1, sizeof(::biblio::TituloRequest)},
  { 12, -1, sizeof(::biblio::PrestamoResponse)},
  { 19, -1, sizeof(::biblio::ConsultaResponse)},
  { 26, -1, sizeof(::biblio::DevolucionResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblio::_IsbnRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblio::_TituloRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblio::_PrestamoResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblio::_ConsultaResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::biblio::_DevolucionResponse_default_instance_),
};

const char descriptor_table_protodef_biblio_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014biblio.proto\022\006biblio\"\033\n\013IsbnRequest\022\014\n"
  "\004ISBN\030\001 \001(\005\"\037\n\rTituloRequest\022\016\n\006titulo\030\001"
  " \001(\t\"1\n\020PrestamoResponse\022\016\n\006estado\030\001 \001(\010"
  "\022\r\n\005fecha\030\002 \001(\t\"7\n\020ConsultaResponse\022\016\n\006e"
  "stado\030\001 \001(\010\022\023\n\013disponibles\030\002 \001(\005\"$\n\022Devo"
  "lucionResponse\022\016\n\006estado\030\001 \001(\0102\220\002\n\nBibli"
  "oteca\022=\n\014PrestamoISBN\022\023.biblio.IsbnReque"
  "st\032\030.biblio.PrestamoResponse\022A\n\016Prestamo"
  "Titulo\022\025.biblio.TituloRequest\032\030.biblio.P"
  "restamoResponse\022=\n\014ConsultaISBN\022\023.biblio"
  ".IsbnRequest\032\030.biblio.ConsultaResponse\022A"
  "\n\016DevolucionISBN\022\023.biblio.IsbnRequest\032\032."
  "biblio.DevolucionResponseb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_biblio_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_biblio_2eproto_sccs[5] = {
  &scc_info_ConsultaResponse_biblio_2eproto.base,
  &scc_info_DevolucionResponse_biblio_2eproto.base,
  &scc_info_IsbnRequest_biblio_2eproto.base,
  &scc_info_PrestamoResponse_biblio_2eproto.base,
  &scc_info_TituloRequest_biblio_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_biblio_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_biblio_2eproto = {
  false, false, descriptor_table_protodef_biblio_2eproto, "biblio.proto", 513,
  &descriptor_table_biblio_2eproto_once, descriptor_table_biblio_2eproto_sccs, descriptor_table_biblio_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_biblio_2eproto::offsets,
  file_level_metadata_biblio_2eproto, 5, file_level_enum_descriptors_biblio_2eproto, file_level_service_descriptors_biblio_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_biblio_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_biblio_2eproto)), true);
namespace biblio {

// ===================================================================

void IsbnRequest::InitAsDefaultInstance() {
}
class IsbnRequest::_Internal {
 public:
};

IsbnRequest::IsbnRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblio.IsbnRequest)
}
IsbnRequest::IsbnRequest(const IsbnRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  isbn_ = from.isbn_;
  // @@protoc_insertion_point(copy_constructor:biblio.IsbnRequest)
}

void IsbnRequest::SharedCtor() {
  isbn_ = 0;
}

IsbnRequest::~IsbnRequest() {
  // @@protoc_insertion_point(destructor:biblio.IsbnRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IsbnRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void IsbnRequest::ArenaDtor(void* object) {
  IsbnRequest* _this = reinterpret_cast< IsbnRequest* >(object);
  (void)_this;
}
void IsbnRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IsbnRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IsbnRequest& IsbnRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IsbnRequest_biblio_2eproto.base);
  return *internal_default_instance();
}


void IsbnRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:biblio.IsbnRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  isbn_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IsbnRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 ISBN = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          isbn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IsbnRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblio.IsbnRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ISBN = 1;
  if (this->isbn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_isbn(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblio.IsbnRequest)
  return target;
}

size_t IsbnRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblio.IsbnRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 ISBN = 1;
  if (this->isbn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_isbn());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IsbnRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblio.IsbnRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const IsbnRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IsbnRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblio.IsbnRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblio.IsbnRequest)
    MergeFrom(*source);
  }
}

void IsbnRequest::MergeFrom(const IsbnRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblio.IsbnRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.isbn() != 0) {
    _internal_set_isbn(from._internal_isbn());
  }
}

void IsbnRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblio.IsbnRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IsbnRequest::CopyFrom(const IsbnRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblio.IsbnRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IsbnRequest::IsInitialized() const {
  return true;
}

void IsbnRequest::InternalSwap(IsbnRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(isbn_, other->isbn_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IsbnRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TituloRequest::InitAsDefaultInstance() {
}
class TituloRequest::_Internal {
 public:
};

TituloRequest::TituloRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblio.TituloRequest)
}
TituloRequest::TituloRequest(const TituloRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  titulo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_titulo().empty()) {
    titulo_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_titulo(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:biblio.TituloRequest)
}

void TituloRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TituloRequest_biblio_2eproto.base);
  titulo_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

TituloRequest::~TituloRequest() {
  // @@protoc_insertion_point(destructor:biblio.TituloRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TituloRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  titulo_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TituloRequest::ArenaDtor(void* object) {
  TituloRequest* _this = reinterpret_cast< TituloRequest* >(object);
  (void)_this;
}
void TituloRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TituloRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TituloRequest& TituloRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TituloRequest_biblio_2eproto.base);
  return *internal_default_instance();
}


void TituloRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:biblio.TituloRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  titulo_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TituloRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string titulo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_titulo();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "biblio.TituloRequest.titulo"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TituloRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblio.TituloRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string titulo = 1;
  if (this->titulo().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_titulo().data(), static_cast<int>(this->_internal_titulo().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "biblio.TituloRequest.titulo");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_titulo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblio.TituloRequest)
  return target;
}

size_t TituloRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblio.TituloRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string titulo = 1;
  if (this->titulo().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_titulo());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TituloRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblio.TituloRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const TituloRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TituloRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblio.TituloRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblio.TituloRequest)
    MergeFrom(*source);
  }
}

void TituloRequest::MergeFrom(const TituloRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblio.TituloRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.titulo().size() > 0) {
    _internal_set_titulo(from._internal_titulo());
  }
}

void TituloRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblio.TituloRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TituloRequest::CopyFrom(const TituloRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblio.TituloRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TituloRequest::IsInitialized() const {
  return true;
}

void TituloRequest::InternalSwap(TituloRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  titulo_.Swap(&other->titulo_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata TituloRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PrestamoResponse::InitAsDefaultInstance() {
}
class PrestamoResponse::_Internal {
 public:
};

PrestamoResponse::PrestamoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblio.PrestamoResponse)
}
PrestamoResponse::PrestamoResponse(const PrestamoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  fecha_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fecha().empty()) {
    fecha_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_fecha(),
      GetArena());
  }
  estado_ = from.estado_;
  // @@protoc_insertion_point(copy_constructor:biblio.PrestamoResponse)
}

void PrestamoResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PrestamoResponse_biblio_2eproto.base);
  fecha_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  estado_ = false;
}

PrestamoResponse::~PrestamoResponse() {
  // @@protoc_insertion_point(destructor:biblio.PrestamoResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PrestamoResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  fecha_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PrestamoResponse::ArenaDtor(void* object) {
  PrestamoResponse* _this = reinterpret_cast< PrestamoResponse* >(object);
  (void)_this;
}
void PrestamoResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PrestamoResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PrestamoResponse& PrestamoResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PrestamoResponse_biblio_2eproto.base);
  return *internal_default_instance();
}


void PrestamoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:biblio.PrestamoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fecha_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  estado_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrestamoResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool estado = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          estado_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string fecha = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fecha();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "biblio.PrestamoResponse.fecha"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PrestamoResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblio.PrestamoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool estado = 1;
  if (this->estado() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_estado(), target);
  }

  // string fecha = 2;
  if (this->fecha().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fecha().data(), static_cast<int>(this->_internal_fecha().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "biblio.PrestamoResponse.fecha");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fecha(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblio.PrestamoResponse)
  return target;
}

size_t PrestamoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblio.PrestamoResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fecha = 2;
  if (this->fecha().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fecha());
  }

  // bool estado = 1;
  if (this->estado() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PrestamoResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblio.PrestamoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const PrestamoResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PrestamoResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblio.PrestamoResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblio.PrestamoResponse)
    MergeFrom(*source);
  }
}

void PrestamoResponse::MergeFrom(const PrestamoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblio.PrestamoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.fecha().size() > 0) {
    _internal_set_fecha(from._internal_fecha());
  }
  if (from.estado() != 0) {
    _internal_set_estado(from._internal_estado());
  }
}

void PrestamoResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblio.PrestamoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrestamoResponse::CopyFrom(const PrestamoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblio.PrestamoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrestamoResponse::IsInitialized() const {
  return true;
}

void PrestamoResponse::InternalSwap(PrestamoResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  fecha_.Swap(&other->fecha_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(estado_, other->estado_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PrestamoResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ConsultaResponse::InitAsDefaultInstance() {
}
class ConsultaResponse::_Internal {
 public:
};

ConsultaResponse::ConsultaResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblio.ConsultaResponse)
}
ConsultaResponse::ConsultaResponse(const ConsultaResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&estado_, &from.estado_,
    static_cast<size_t>(reinterpret_cast<char*>(&disponibles_) -
    reinterpret_cast<char*>(&estado_)) + sizeof(disponibles_));
  // @@protoc_insertion_point(copy_constructor:biblio.ConsultaResponse)
}

void ConsultaResponse::SharedCtor() {
  ::memset(&estado_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&disponibles_) -
      reinterpret_cast<char*>(&estado_)) + sizeof(disponibles_));
}

ConsultaResponse::~ConsultaResponse() {
  // @@protoc_insertion_point(destructor:biblio.ConsultaResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConsultaResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ConsultaResponse::ArenaDtor(void* object) {
  ConsultaResponse* _this = reinterpret_cast< ConsultaResponse* >(object);
  (void)_this;
}
void ConsultaResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConsultaResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConsultaResponse& ConsultaResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConsultaResponse_biblio_2eproto.base);
  return *internal_default_instance();
}


void ConsultaResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:biblio.ConsultaResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&estado_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&disponibles_) -
      reinterpret_cast<char*>(&estado_)) + sizeof(disponibles_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConsultaResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool estado = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          estado_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 disponibles = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          disponibles_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConsultaResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblio.ConsultaResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool estado = 1;
  if (this->estado() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_estado(), target);
  }

  // int32 disponibles = 2;
  if (this->disponibles() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_disponibles(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblio.ConsultaResponse)
  return target;
}

size_t ConsultaResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblio.ConsultaResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool estado = 1;
  if (this->estado() != 0) {
    total_size += 1 + 1;
  }

  // int32 disponibles = 2;
  if (this->disponibles() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_disponibles());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConsultaResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblio.ConsultaResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ConsultaResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConsultaResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblio.ConsultaResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblio.ConsultaResponse)
    MergeFrom(*source);
  }
}

void ConsultaResponse::MergeFrom(const ConsultaResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblio.ConsultaResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.estado() != 0) {
    _internal_set_estado(from._internal_estado());
  }
  if (from.disponibles() != 0) {
    _internal_set_disponibles(from._internal_disponibles());
  }
}

void ConsultaResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblio.ConsultaResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConsultaResponse::CopyFrom(const ConsultaResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblio.ConsultaResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConsultaResponse::IsInitialized() const {
  return true;
}

void ConsultaResponse::InternalSwap(ConsultaResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ConsultaResponse, disponibles_)
      + sizeof(ConsultaResponse::disponibles_)
      - PROTOBUF_FIELD_OFFSET(ConsultaResponse, estado_)>(
          reinterpret_cast<char*>(&estado_),
          reinterpret_cast<char*>(&other->estado_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ConsultaResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void DevolucionResponse::InitAsDefaultInstance() {
}
class DevolucionResponse::_Internal {
 public:
};

DevolucionResponse::DevolucionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:biblio.DevolucionResponse)
}
DevolucionResponse::DevolucionResponse(const DevolucionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  estado_ = from.estado_;
  // @@protoc_insertion_point(copy_constructor:biblio.DevolucionResponse)
}

void DevolucionResponse::SharedCtor() {
  estado_ = false;
}

DevolucionResponse::~DevolucionResponse() {
  // @@protoc_insertion_point(destructor:biblio.DevolucionResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void DevolucionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void DevolucionResponse::ArenaDtor(void* object) {
  DevolucionResponse* _this = reinterpret_cast< DevolucionResponse* >(object);
  (void)_this;
}
void DevolucionResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DevolucionResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DevolucionResponse& DevolucionResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DevolucionResponse_biblio_2eproto.base);
  return *internal_default_instance();
}


void DevolucionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:biblio.DevolucionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  estado_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DevolucionResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool estado = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          estado_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DevolucionResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:biblio.DevolucionResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool estado = 1;
  if (this->estado() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_estado(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biblio.DevolucionResponse)
  return target;
}

size_t DevolucionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biblio.DevolucionResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool estado = 1;
  if (this->estado() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DevolucionResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biblio.DevolucionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const DevolucionResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DevolucionResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biblio.DevolucionResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biblio.DevolucionResponse)
    MergeFrom(*source);
  }
}

void DevolucionResponse::MergeFrom(const DevolucionResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biblio.DevolucionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.estado() != 0) {
    _internal_set_estado(from._internal_estado());
  }
}

void DevolucionResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biblio.DevolucionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DevolucionResponse::CopyFrom(const DevolucionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biblio.DevolucionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DevolucionResponse::IsInitialized() const {
  return true;
}

void DevolucionResponse::InternalSwap(DevolucionResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(estado_, other->estado_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DevolucionResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace biblio
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::biblio::IsbnRequest* Arena::CreateMaybeMessage< ::biblio::IsbnRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblio::IsbnRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::biblio::TituloRequest* Arena::CreateMaybeMessage< ::biblio::TituloRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblio::TituloRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::biblio::PrestamoResponse* Arena::CreateMaybeMessage< ::biblio::PrestamoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblio::PrestamoResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::biblio::ConsultaResponse* Arena::CreateMaybeMessage< ::biblio::ConsultaResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblio::ConsultaResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::biblio::DevolucionResponse* Arena::CreateMaybeMessage< ::biblio::DevolucionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::biblio::DevolucionResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
